# OAUTH KEYS
OAUTH_CONSUMER_KEY = 'OAUTH_API_KEYS'
OAUTH_TOKEN = 'OAUTH_TOKEN'

# TRELLO API ENDPOINTS
TRELLO_API_URL = 'https://api.trello.com/1/'
CHECKITEMS_CHECKLIST_ENDPOINT = TRELLO_API_URL + 'checklists/{}/checkItems'
CHECKITEM_CARD_ENDPOINT = TRELLO_API_URL + 'cards/{}/checkItem/{}'
CHECKLISTS_CARD_ENDPOINT = TRELLO_API_URL + 'cards/{}/checklists'
CARD_LISTS_ENDPOINT = TRELLO_API_URL + 'lists/{}/cards'
LISTS_BOARD_ENDPOINT = TRELLO_API_URL + 'boards/{}/lists'
BOARD_USER_ENDPOINT = TRELLO_API_URL + 'members/me/boards'